[IO2508H19417889]
dpi_x = 800
dpi_y = 800
poll_rate = 1000
logo_active = True
logo_brightness = 75
logo_effect = breathSingle
logo_colors = 0 255 0 0 255 255 0 0 255
logo_speed = 1
logo_wave_dir = 1

