listener {
    timeout = 330  # 5.5min == 330
    on-timeout = hyprlock & hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' # screen on when activity is detected after timeout has fired.
}
